
remote_theme: jeffreytse/jekyll-theme-yat@v1.10.0
title: Hacking Odessey
author: Vamsi Surakarapu
description: >-
  Hack-Odyssey is a personal portfolio where I showcase my skills and projects in multiple fields like cybersecurity, Java, machine learning, web development, blockchain, and more. It's a collection of real-world applications that highlight my problem-solving abilities and creativity. This portfolio reflects my journey through different domains, demonstrating how I tackle challenges and come up with innovative solutions. Whether it's securing systems, building apps, or diving into new technologies, Hack-Odyssey is where you can see how I apply my knowledge in practice.
yat: 
  date_format: "%b %d, %Y"
defaults:
  home:
      heading: "Hacking Odessey"
      subheading: "Tempat pelarian dikala tomi gabut gak ada kerjaan"
      banner: "home.jpg"
favicon: "https://avatars.githubusercontent.com/u/85192850"
night_mode: "on"
# brand_color: "#389092"
header_pages:
  - index.html
  - categories.html
  - tags.html
  - archives.html
  - about.html

# Pagination setting
paginate: 5

disqus:
  shortname: "Hack Odessey"
